version: '2'
services:
    review-mongodb:
        container_name: review-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb review-mongodb-config
    review-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    review-mongodb-config:
        image: mongo:3.2.10
        container_name: review-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
