version: '2'
services:
    review-mongodb:
        container_name: review-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/review/mongodb/:/data/db/
